version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - rm package-lock.json
      - npm ci
      - npm install
      - npm install -g cdk
      - npm run build
